name: Package on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/916415899
        chmod 600 ~/.ssh/916415899
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Grant execute permission for deploy script
      run: chmod +x ./deploy.sh

    - name: Configure Git
      run: |
        git config --global user.name "ningmengchongshui"
        git config --global user.email "916415899@qq.com"

    - name: Run build script
      run: ./deploy.sh
